[project]
name = "FSTmorph"
version = "0.1.3"
description = "A package for building FST-based morphological analyzers and generators from spreadsheets"
readme = "README.md"
requires-python = ">=3.9"

authors = [
{ name = "Miikka Silfverberg", email = "msilfver@mail.ubc.ca"},
{ name = "Anna Stacey", email = "anna.stacey@ubc.ca"},
{ name = "Christopher Hammerly", email = "chris.hammerly@ubc.ca"},
]

dependencies = [
"pandas>=2.0.1",
"click>=8.1.3",
"jinja2>=3.1.3",
"PyYAML>=6.0",
]

[tool.poetry]
packages = [
{ include = "fstmorph" },
]

[tool.poetry.group.dev.dependencies]
pylint = "^3.2.3"
pytest = "^8.2.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

